name: Python application test with Github Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: set up python3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: install dependencies
      run: 
        make install
    - name: Lint w/ pyLint
      run:
        make lint
    - name: Test w/ pytest.
      run:
        make test
