name: Python application test with Github Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: set up python3.8 
      uses: actions/setup-python@v1
      with:
        python-version: 3.8 
    - name: install dependencies
      run: 
        make install 
    - name: Lint w/ pyLint
      run: 
        make lint
    - name: Test w/ pytest.
      run: 
        make test
